command: ['streamlit', 'run', 'app.py']

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: INVENTORY_TABLE
    valueFrom: inventory-table

  - name: SALES_HISTORY_TABLE
    valueFrom: sales-history-table

  - name: SETTINGS_TABLE
    valueFrom: settings-table